site_name: Wiki Transer

theme:
  name: material
  favicon: images/favicon.png
  icon:
    logo: material/book-open-blank-variant
  palette:
    primary: black
    accent: deep purple
  features: 
    - navigation.instant    
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - content.code.copy

markdown_extensions: 
  - toc:
      permalink: true
  - md_in_html
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - css/extra.css

plugins:
    - search
    - awesome-pages